### PR TITLE
docs: modify perception architecture in node diagram

### PR DESCRIPTION
**Pull request by Shin-kyoto**
Signed-off-by: Shin-kyoto <58775300+Shin-kyoto@users.noreply.github.com>

## Description

- Add links to nodes in perception.
- Add merger and validater.
- Modify graph in occupancy_grid_map.

node_diagram

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The Reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by shmpwk** [comment]
Great work! Do you mean object_association_merger has 3 type?

**Comment by Shin-kyoto** [comment]
> Great work! Do you mean there are 3 nodes of object_association_merger? I could not find them in the source code.

@shmpwk 

You can find them [here](https://github.com/autowarefoundation/autoware.universe/blob/50701301325402063dfff065de2170a256fdaf42/launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_fusion_based_detection.launch.xml#L241).

**Comment by shmpwk** [comment]
Thank you! 
I agree with you that they show up as `object_association_merger` in the node diagram for simplicity though they have different node name by `anon` [here](https://github.com/autowarefoundation/autoware.universe/blob/main/perception/object_merger/launch/object_association_merger.launch.xml#L10).

**Review by soblin — APPROVED** [review]
LGTM

**Review by shmpwk — APPROVED** [review]

**Comment by Shin-kyoto** [comment]
@scepter914 Can you review this PR?

**Comment by Shin-kyoto** [comment]
Add object_lanelet_filter
node_diagram

**Review by miursh — COMMENTED** [review]
The position of object_range_splitter is different from [camera-lidar-fusion launch](https://github.com/autowarefoundation/autoware.universe/blob/main/launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_fusion_based_detection.launch.xml).
This one is only applied to camera_lidar_fusion not clustering.

**Review by miursh — COMMENTED** [review]
The input for yolo or yolox is image_rect_color not image_raw

**Comment by miursh** [comment]
There are some typos in tooltips of object_merger. (e.g. "etection")

**Comment by Shin-kyoto** [comment]
> The position of object_range_splitter is different from [camera-lidar-fusion launch](https://github.com/autowarefoundation/autoware.universe/blob/main/launch/tier4_perception_launch/launch/object_recognition/detection/camera_lidar_fusion_based_detection.launch.xml). This one is only applied to camera_lidar_fusion pipeline not clustering pipeline .

Thank you for your review!
I fixed them.

node_diagram

**Review by miursh — APPROVED** [review]
LGTM :+1:

**Comment by scepter914** [comment]
> @scepter914 Can you review this PR?

This PR  looks good to me :+1
I guess you forgot assigning me as reviewer, so I leave a comment.

**Pull request merged**
