### PR TITLE
docs(tutorial): add readme file for centerpoint_vs_centerpoint-tiny 

### PR DESCRIPTION
**Pull request by YueChuCheng**
Signed-off-by: YueChuCheng <maggie9907@gmail.com>

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The Reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [x] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by miursh** [comment]
@YueChuCheng Is this document the same as [this](https://github.com/YueChuCheng/autoware-documentation/blob/main/docs/tutorials/centerpoint_vs_centerpoint-tiny/centerpoint_vs_centerpoint-tiny.md)?

**Comment by YueChuCheng** [comment]
> @YueChuCheng Is this document the same as [this](https://github.com/YueChuCheng/autoware-documentation/blob/main/docs/tutorials/centerpoint_vs_centerpoint-tiny/centerpoint_vs_centerpoint-tiny.md)?

Yes, these two are the same document. Is there anything inappropriate?

**Comment by miursh** [comment]
@YueChuCheng 
Sorry for the delay in getting back to you. I spoke with some folks and we decided that there is no need to put the same document in autoware-documentation. May I close this pull request?
Instead, we are going to add a reference to your [doc](https://github.com/YueChuCheng/autoware-documentation/blob/main/docs/tutorials/centerpoint_vs_centerpoint-tiny/centerpoint_vs_centerpoint-tiny.md) in open-ad-kit-docs [here](https://github.com/autowarefoundation/open-ad-kit-docs/blob/main/docs/version-2.0/start-guide/how-to-run-autoware/index.md)

**Comment by YueChuCheng** [comment]
> 

Sounds very reasonable! It is fine for me. Thanks for your reply.

**Comment by miursh** [comment]
@YueChuCheng I made a PR https://github.com/autowarefoundation/open-ad-kit-docs/pull/43

**Pull request closed without merging**
