### PR TITLE
docs(contributing): update contributing guidelines

### PR DESCRIPTION
**Pull request by LalithVipulananthan**
## Description

- Rearranged the entire page using [Atom](https://github.com/atom/atom/blob/master/CONTRIBUTING.md
) and [Angular](https://github.com/angular/angular/blob/master/CONTRIBUTING.md
)'s contribution guides as a reference.
- Main changes were to add "How can I get help?" and "What should I know before I get started?" sections
- Code of Conduct left in place since this is standard for other OSS projects, but reworded the text slightly and added the conduct email address for reports
- ROS 2 docs link was removed because it is too specific to ROS 2. If there are parts that we think are useful, then we should add them explicitly to this document

Signed off by: Lalith Vipulananthan <lalith.vipulananthan@tier4.jp>

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The Reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by kenji-miyake** [comment]
@LalithVipulananthan Could you add the `documentation` label? It will trigger `deploy-docs`.
image

(Of course, I can do it, but as your practice.)

**Comment by kenji-miyake** [comment]
@LalithVipulananthan And could you fix the title? :pray: 
https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/#semantic-pull-request

**Comment by LalithVipulananthan** [comment]
> @LalithVipulananthan And could you fix the title? 🙏 https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/#semantic-pull-request

I just tried doing this via command line as per the GitHub documentation, but after authorising the Git Credential Manager, the following error occurred:
```
 ! [remote rejected] update-contributing-support-pages -> update-contributing-support-pages (permission denied)
error: failed to push some refs to 'https://github.com/Talvalin/autoware-documentation.git'
```

I think it might just be easier to close the PR and resubmit it.

**Comment by LalithVipulananthan** [comment]
It seems that I forked the repository to my personal GitHub account rather than my work one, so to clean this up properly I need to fork to my work account then resubmit the PR, so I will close this one out. Apologies for the mixup!

**Pull request closed without merging**
