### PR TITLE
docs: add the carla simulator page under digital twin

### PR DESCRIPTION
**Pull request by evshary**
## Description

Add the Carla simulator page, which includes several projects able to bridge Autoware and Carla.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The Reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by evshary** [comment]
Before merging the PR, I'll ask the community to add more projects to the pages.

**Comment by evshary** [comment]
I have asked for permission to put other projects on the page.
https://github.com/orgs/autowarefoundation/discussions/3391#discussioncomment-8391628
https://github.com/orgs/autowarefoundation/discussions/2828#discussioncomment-8408457
I think it's ready for review now.

**Comment by evshary** [comment]
Hi @mitsudome-r
It would be great if you could take a look at the changes. 
Please let me know if you have any comments. Thank you.

**Review by mitsudome-r — APPROVED** [review]
LGTM!

**Pull request merged**
