### PR TITLE
feat: add roi_pointcloud_fusion

### PR DESCRIPTION
**Pull request by badai-nguyen**
## Description
Update node diagram regarding PR [#4681](https://github.com/autowarefoundation/autoware.universe/pull/4681)

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The Reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by miursh — COMMENTED** [review]
@badai-nguyen 
Is this correct? I think roi_pointcloud_fusion output `roi_cluster/clusters` and `cluster_merger` is added.

image

**Comment by miursh** [comment]
Ah, sorry I get it. This PR is a bit old one....

**Comment by badai-nguyen** [comment]
@miursh I am sorry, this PR was created before changing to roi_based_clustering. I will check and update the diag if needed.

**Comment by badai-nguyen** [comment]
I close this since it is fixed here https://github.com/autowarefoundation/autoware-documentation/pull/537

**Pull request closed without merging**
