### PR TITLE
feat(how-to): rename how to guide section

### PR DESCRIPTION
**Pull request by LalithVipulananthan**
## Description

Rename "how-to guide" section to "advanced" and move to the tutorials folder

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The Reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by LalithVipulananthan** [comment]
#126 is unfortunately blocked due to a merge conflict that I wasn't able to resolve, so I thought it might be quicker to submit a clean new PR instead.

**Review by soblin — APPROVED** [review]

**Comment by kenji-miyake** [comment]
@LalithVipulananthan I'm sorry but I wanted you to wait for my review. :cry: 
I personally think that:
- `Tutorial` should be step-by-step documents that we want everyone to do.
- `How-to guides` should be other documents that we don't think everyone needs them.

So I recommend reverting this. What do you think?

**Comment by kenji-miyake** [comment]
Also, if you want to change the structure, which is a relatively big change, you had to write more background information and reasons in the description so that others can understand it.

**Comment by LalithVipulananthan** [comment]
@kenji-miyake Based on your [comment on @soblin's original PR](https://github.com/autowarefoundation/autoware-documentation/pull/126#issuecomment-1138319079), I had assumed that you were okay with the proposed structural change and so that's why I didn't give so much detail for this PR and also why I merged it as soon as @soblin approved the PR. 

In summary, you think that the current pages that we have under the "how-to guides" sections should stay where they were originally? 

Whilst we are here, @kminoda was proposing that the scenario testing tutorials should be moved into an advanced tutorials section, which kind of overlaps with this PR. 

Perhaps it would be an idea to create a Design discussion to make proposals and suggestions on how to handle advanced tutorials and how-to guides?

**Comment by kenji-miyake** [comment]
@LalithVipulananthan I'm sorry for my unclear comment. :bow: But I just commented and didn't approve it.

> that's why I didn't give so much detail for this PR

It wasn't good because the reasons of changes aren't clear if I see #126.

> Whilst we are here, @kminoda was proposing that the scenario testing tutorials should be moved into an advanced tutorials section, which kind of overlaps with this PR.

I think it's good, but to do that, we didn't have to move all contents from how-to guides.

> Perhaps it would be an idea to create a Design discussion to make proposals and suggestions on how to handle advanced tutorials and how-to guides?

Yes, it's a good idea. But before that, I think it's good to revert this to avoid confusion.

**Comment by kenji-miyake** [comment]
Just click this button. I'll do it this time.
image

**Pull request merged**
