### PR TITLE
docs: change links of perception nodes in node diagram

### PR DESCRIPTION
**Pull request by Shin-kyoto**
Signed-off-by: Shin-kyoto <58775300+Shin-kyoto@users.noreply.github.com>

## Description

- Links of perception nodes are old(autoware.iv ver.), so I changed these links into autoware.universe ver.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The Reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by kminoda** [comment]
Which part of the diagram is modified?

**Review by kminoda — COMMENTED** [review]
Which part of the diagram is modified?

-> Sorry I misread the title. The links are modified. Never mind.

**Review by kminoda — COMMENTED** [review]
One minor comment: How about updating the links of `obstacle_segmentation` and `occupancy_grid_map` as well?

**Comment by shmpwk** [comment]
Are these still used?
https://github.com/tier4/autoware.iv/tree/develop/sensing/preprocessor/pointcloud/laserscan_to_occupancy_grid_map
https://github.com/tier4/pointcloud_to_laserscan

**Comment by Shin-kyoto** [comment]
> How about updating the links of obstacle_segmentation and occupancy_grid_map as well?

To tell the truth, I do not know links for these nodes, so I did not change them. 

- voxel_grid_filter
- outlier_filter
- obstacle_segmentation
  - crop_box_filter
  - common_ground_filter
  - pointcloud_to_laserscan
  - laserscan_to_occupancy_grid_map

**Comment by Shin-kyoto** [comment]
> And traffic light link is old

Sorry, which one is old?
(I checked it, but I could not find old link...)

**Comment by shmpwk** [comment]
> (I checked it, but I could not find old link...)

Sorry but it was my mistakes

**Review by kminoda — APPROVED** [review]
LGTM (obstacle segmentation links can be updated later)

**Comment by shmpwk** [comment]
According to https://github.com/autowarefoundation/autoware.universe/blob/0d9c92fa8ae31da658be109347d63201faede6e1/launch/tier4_perception_launch/launch/obstacle_segmentation/ground_segmentation/ground_segmentation.launch.py#L350-L425 , 


- https://github.com/autowarefoundation/autoware.universe/tree/main/perception/compare_map_segmentation
- https://github.com/autowarefoundation/autoware.universe/blob/main/sensing/pointcloud_preprocessor/docs/downsample-filter.md  (which is simmilar to VoxelGridDownsampleFilterComponent?)
- https://github.com/autowarefoundation/autoware.universe/blob/main/sensing/pointcloud_preprocessor/docs/voxel-grid-outlier-filter.md

**Pull request merged**
