### PR TITLE
docs(node-diagram): add routing api

### PR DESCRIPTION
**Pull request by TakaHoribe**
## Description

Add routing api in the node diagram

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The Reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by kosuke55** [comment]
wow, thanks!

image


```
/planning/mission_planning/change_route
/planning/mission_planning/change_route_points
```
are missing?

**Comment by kosuke55** [comment]
it may be not necessary to write and make confusing but `/planning/mission_planning/goal` is published directly from rviz

```
$ ros2 topic info /planning/mission_planning/goal -v
Type: geometry_msgs/msg/PoseStamped

Publisher count: 1

Node name: rviz2
Node namespace: /
Topic type: geometry_msgs/msg/PoseStamped
Endpoint type: PUBLISHER
GID: 01.10.00.67.9c.c0.36.4f.38.d3.25.d9.00.00.84.03.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: RELIABLE
  History (Depth): KEEP_LAST (5)
  Durability: VOLATILE
  Lifespan: Infinite
  Deadline: Infinite
  Liveliness: AUTOMATIC
  Liveliness lease duration: Infinite

Subscription count: 1

Node name: routing_adaptor
Node namespace: /default_ad_api/helpers
Topic type: geometry_msgs/msg/PoseStamped
Endpoint type: SUBSCRIPTION
GID: 01.10.d2.a5.ad.ae.cd.e9.d9.00.70.3b.00.00.15.04.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: RELIABLE
  History (Depth): KEEP_LAST (3)
  Durability: VOLATILE
  Lifespan: Infinite
  Deadline: Infinite
  Liveliness: AUTOMATIC
  Liveliness lease duration: Infinite
```

**Comment by TakaHoribe** [comment]
@kosuke55 
>/planning/mission_planning/change_route
/planning/mission_planning/change_route_points
are missing?

Thank you! I updated.


>/planning/mission_planning/goal is published directly from rviz

I'm being confused. How these messages are differentiated?

**Comment by kosuke55** [comment]
> Thank you! I updated.

change_route and change_route_points are called from routing 

https://github.com/autowarefoundation/autoware.universe/blob/477ce95a1975773e426458f986b9a8a8c43a89f7/system/default_ad_api/src/routing.cpp#L36-L37




> I'm being confused. How these messages are differentiated?

It's just FYI :pray: 

This is a message for directly inputting a goal without api service, and is used in rviz's `SetGoal` button

The flow is
[rviz2] -`/planning/mission_planning/goal `-> [/default_ad_api/helpers/routing_adaptor] -`set_route_points`-> [/default_ad_api/node/routing] -`set_route_points`-> [mission_planner] 

I think the topic name remains the same as in the old interface, so it might be better to rename to like `rviz/routing/goal`, but need to consider compatibility with other tools.

**Comment by kosuke55** [comment]
> so it might be better to rename to like rviz/routing/goal

- https://github.com/autowarefoundation/autoware.universe/blob/main/system/default_ad_api_helpers/ad_api_adaptors/launch/rviz_adaptors.launch.xml#L12
- rviz config 

> but need to consider compatibility with other tools.

I think that main tools already use api, but some tools still use the topic like 
https://github.com/tier4/autoware-functional-tests/blob/main/autoware_functional_tests/autoware/pub.py#L27-L29
so need to check the scope of influence.

**Comment by kosuke55** [comment]
> I think that main tools already use api, but some tools still use the topic like

ah, scenario_simulator_v2 also uses the topic, but will move to use api in the near future.

https://github.com/tier4/scenario_simulator_v2/blob/master/external/concealer/include/concealer/field_operator_application_for_autoware_universe.hpp#L112

**Comment by TakaHoribe** [comment]
@kosuke55 Thank you for the information. I updated the diagram. Would you review again?

**Comment by kosuke55** [comment]
not the image of https://github.com/autowarefoundation/autoware-documentation/pull/450#issuecomment-1712788163 but your updating is correct..!:pray:
image

**Review by kosuke55 — APPROVED** [review]
LGTM!!

**Pull request merged**
