### PR TITLE
chore: changed the package name imu_corrector to autoware_imu_corrector

### PR DESCRIPTION
**Pull request by knzo25**
## Description
Documentation counterpart of https://github.com/autowarefoundation/autoware.universe/pull/8222

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The Reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by knzo25** [comment]
note: pre-commit does not pass since it looks for links that will only exist when the main PR is merged

**Review by TaikiYamada4 — APPROVED** [review]
LGTM!

**Review by ismetatabay — APPROVED** [review]

**Comment by knzo25** [comment]
@ismetatabay 
the parent PR was merged so this one should be ok as well :pray:  
(as far as I understand the person who made the comment should resolve it)

**Comment by ismetatabay** [comment]
@knzo25 sorry for the late response, I marked it as resolved thanks! :raised_hands:

**Review by YamatoAndo — APPROVED** [review]

**Pull request merged**
