### PR TITLE
docs: add pull request guidelines

### PR DESCRIPTION
**Pull request by kenji-miyake**
Related: #6

### CODE REVIEW

**Comment by isamu-takagi** [comment]
How about adding an explanation of what is a small or standard change in [PR template](https://github.com/autowarefoundation/autoware/pull/56/files#diff-18813c86948efc57e661623d7ba48ff94325c9b5421ec9177f724922dd553a35R1)?
And It is useful to refer to it from the template.

**Comment by kenji-miyake** [comment]
@isamu-takagi Okay, I'll add a sentence like this: `Confirm our contribution guidelines before submitting a pull request.`

**Review by xmfcx — APPROVED** [review]
I've read them, haven't used the instructions for committing yet so cannot comment if they are all working.

But they seem good.

**Comment by kenji-miyake** [comment]
Thank you!
I'll merge this after #43.

**Pull request merged**
