### PR TITLE
feat(how-to-guides): add debug autoware guides

### PR DESCRIPTION
**Pull request by cyn-liu**
Signed-off-by: Cynthia Liu <cynthia.liu@autocore.ai>

## Description

Add `debug Autoware` tutorial in `how to guides`.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The Reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [x] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by mitsudome-r** [comment]
I will check with our developers if they have any additional ways to debug autoware.

**Comment by mitsudome-r** [comment]
Do you think this content is covered by https://autowarefoundation.github.io/autoware-documentation/main/contributing/coding-guidelines/ros-nodes/console-logging/?

**Comment by cyn-liu** [comment]
> Do you think this content is covered by https://autowarefoundation.github.io/autoware-documentation/main/contributing/coding-guidelines/ros-nodes/console-logging/?

Both output log information on the console.

**Comment by xmfcx** [comment]
I also think everything in this PR is also contained in https://autowarefoundation.github.io/autoware-documentation/main/contributing/coding-guidelines/ros-nodes/console-logging/

If you come up with some more ways of debugging nodes like:
- Printing debug messages (this pr only covers this, you can link mentioned doc page for this)
- Using a debugger (like using `gdb` or CLion's debugger or VSCode) with breakpoints
- Using visualization tools like `rviz2` and `rqt`

Used [ChatGPT](https://chat.openai.com/chat) with "How do you debug a ros2 node?" prompt to generate these:
- Using command line tools like `ros2 topic`, `ros2 service`, and `ros2 action`, can be useful for debugging a node. For example, `ros2 topic echo` can be used to see the messages being published on a specific topic, or `ros2 service call` can be used to test a service provided by a node.
- Using bag files: You can record the ROS2 messages being published and subscribed to by your node using bag files. You can then playback the bag files to debug your node and see how it is interacting with the rest of the system.
- Using a system profiler: A system profiler, such as `perf`, can be used to profile the performance of your node and identify any bottlenecks or issues.
- Using a memory profiler: A memory profiler, such as `valgrind`, can be used to identify any memory leaks or issues in your node.
- Using a static code analyzer: A static code analyzer, such as `cppcheck`, can be used to identify potential issues in your node's code, such as syntax errors or logical bugs.

**Comment by xmfcx** [comment]
I will convert it into draft if you'd like to restructure the PR.

**Comment by cyn-liu** [comment]
@xmfcx 
Thanks for your advice, it‘s very helpful for me. I will modify this document.

**Comment by cyn-liu** [comment]
Hi @mitsudome-r  @xmfcx  will you help us to review it?

Best regards,
Cynthia

**Review by xmfcx — APPROVED** [review]
Thanks for the great work!

**Pull request merged**
