### PR TITLE
docs: update Fixposition documentation

### PR DESCRIPTION
**Pull request by fixposition-support**
## Description

This PR:
- Fixes the title for Fixposition sensor
- Adds links to helper utilities

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The Reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [x] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by souryavarenya** [comment]
On behalf of @fixposition-support, unsure why the DCO check is failing. Can the maintainers have a look at this?

**Comment by souryavarenya** [comment]
@isamu-takagi @mitsudome-r I'm assuming you're the maintainers here, could you please look into this?

**Comment by isamu-takagi** [comment]
@souryavarenya @fixposition-support 
I don't know why, but the action sometimes doesn't get triggered. If I make any commits it works, so I merged the main branch.

There is an error in the spell check, so please register the word according to [this page](https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/ci-checks/#spell-check-differential). In this case, I think it's easier to use `cspell:ignore`.

**Comment by fixposition-support** [comment]
@isamu-takagi Thank you for the response. I now added a spell ignore. Please let me know if I must do anything else.

**Review by isamu-takagi — APPROVED** [review]
LGTM

**Pull request merged**
