### PR TITLE
docs(autoware-interfaces): add autoware interface design

### PR DESCRIPTION
**Pull request by isamu-takagi**
Signed-off-by: Takagi, Isamu <isamu.takagi@tier4.jp>

## Description

Add the document of Autoware interface design. 
https://github.com/autowarefoundation/autoware/discussions/41

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The Reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by isamu-takagi** [comment]
Remove version from API name by this discussion.
https://github.com/autowarefoundation/autoware.universe/pull/704#discussion_r856837029

**Comment by isamu-takagi** [comment]
@mitsudome-r 
Since I think we need a prototype to discuss the API, I'm working on implementing it. So I would like to merge the documents for it as well. What do you think? https://github.com/autowarefoundation/autoware/discussions/99#discussioncomment-2584621

**Review by mitsudome-r — APPROVED** [review]
LGTM

**Comment by mitsudome-r** [comment]
The CI seems to be failing, but it is already failing in master so we will fix it with another PR.

**Pull request merged**
