### PR TITLE
feat: add code owners documentation

### PR DESCRIPTION
**Pull request by xmfcx**
## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The Reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by esteve — APPROVED** [review]
@xmfcx LGTM, thanks

**Comment by esteve** [comment]
@xmfcx I've reviewed this PR before the latest changes :sweat_smile: Are there more changes coming or should I review the PR as is now?

**Comment by xmfcx** [comment]
So fast @esteve :D I am also reviewing it with chatgpt and will do some wording and formatting improvements with that but the core information will stay the same.

**Comment by xmfcx** [comment]
Alright it's ready now 😁

**Comment by xmfcx** [comment]
Once https://github.com/autowarefoundation/autoware-documentation/actions/runs/8923243027 is done,
https://autowarefoundation.github.io/autoware-documentation/pr-546/contributing/pull-request-guidelines/code-owners/

will be updated too.

**Comment by xmfcx** [comment]
I'll merge it for now, if you have any reviews or comments, I will open up a new PR to also apply them.

**Pull request merged**
