### PR TITLE
docs(tutorial): rename tutorial subsections

### PR DESCRIPTION
**Pull request by kminoda**
Signed-off-by: kminoda <koji.m.minoda@gmail.com>

## Description
Although the readers expect the tutorial page to be a "tutorial" for total Autoware beginners, the title of the subsections in the tutorial may be not descriptive enough.

For example, it is confusing to the readers that two pages with the exact same name of "planning simulation" exist both in the "Adhoc simulation" and "Scenario simulation" sections, because:
- readers may misunderstand "Adhoc simulation > planning simulation" and "Scenario simulation > planning simulation" as two independent functions, whereas the latter one is dependent on the former one
- the words "adhoc" and "scenario" themselves are (IMHO) not that common

This PR aims to provide more concrete titles for these subsections to clarify the goal of each page. To this end, I propose to rename the title of subsections as follows:
- Adhoc Simulation -> Simulating Autoware
  - Planning simulation -> Using a planning simulation
  - Rosbag replay simulation -> Using a rosbag replay simulation
  - Digital twin simulation -> Using a digital twin simulation
- Scenario Simulation -> Running a scenario test
  - Planning simulation -> Running a scenario test with a planning simulation
  - Rosbag replay simulation -> Running a scenario test with a rosbag replay simulation
  - Digital twin simulation -> Running a scenario test with a digital twin simulation

I believe, with this modification, the difference between "adhoc simulation" and "scenario simulation" will be more clear to the readers. 
Any comments are welcome including the improvement of the rename.

(Also, I think it is also common to start the title of the pages in tutorial section with "[verb]ing ~" in ROS community. ex: [ROS tutorial](http://wiki.ros.org/ROS/Tutorials), [ROS2 tutorial](https://docs.ros.org/en/foxy/Tutorials.html))

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The Reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by kenji-miyake** [comment]
Since simply this is a problem with English technical writing, I'll leave the decision to Lalith-san.

**Comment by kminoda** [comment]
I will leave this as a draft until https://github.com/autowarefoundation/autoware-documentation/pull/124 is merged.

**Comment by LalithVipulananthan** [comment]
> I will leave this as a draft until #124 is merged.

#124 is now merged!

**Comment by kminoda** [comment]
@LalithVipulananthan I appreciate it if you could give me some feedback on this PR. Thanks!

**Comment by kminoda** [comment]
@LalithVipulananthan I appreciate it if you could give me some feedback on this PR. Thanks!

**Comment by LalithVipulananthan** [comment]
Hmm. I see the reasoning behind making the changes, but even if we make these changes, I feel that someone will still ask "So what's the difference between `Simulating Autoware` and `Running a scenario test`?". I also note that we refer to "scenarios" in the [scenario_simulator_v2 documentation](https://tier4.github.io/scenario_simulator_v2-docs/), so if the word is considered to be uncommon then perhaps it is something that we can define in one of these tutorials.

We could potentially split these into `Basic simulations` and `Advanced simulations`? Possible overlap with #126 though, as we would have basic and advanced tutorials, then basic and advanced simulations within the basic tutorials section. 😅

**Comment by kminoda** [comment]
Thank you for the comment!
First, the subtitle `Simulating Autoware` may be inappropriate. Maybe something like `Running simulations` is better.

I agree that `Basic simulations` and `Advanced simulations` is better than the current one in the main branch, but it is still confusing since they seem to be two parallel concepts, while in reality "scenario planning simulation" is built on "planning simulator (=adhoc planning simulation)". 

I didn't mention it in the description, but I think that "Scenario Simulation" or "Running a scenario test" should be eventually moved to "How-to guides" section, since it is not for total beginners (e.g. a student or some researchers in University who are completely new to Autoware) but rather for intermediate users (e.g. autonomous driving researchers or engineers who already have developed their algorithms based on Autoware and want to perform a quantitative evaluation on a scenario basis to maintain reproducibility). 
If the above is achieved and "Simulating Autoware" and "Running a scenario test" is no longer in the same page, then I think that the question `So what's the difference between Simulating Autoware and Running a scenario test` won't arise.

**Comment by LalithVipulananthan** [comment]
Unfortunately, I do not have a suggestion that I am 100% happy with, but how about this?

- Autoware Simulations
  - Using the Planning Simulator
  - Using the Rosbag Replay Simulator
  - Using the Digital twin Simulator
- Autoware Scenario Tests
  - Running a scenario test with the Planning Simulator
  - Running a scenario test with the Rosbag Replay Simulator
  - Running a scenario test with the Digital Twin Simulator

**Comment by kminoda** [comment]
@LalithVipulananthan (Apologies for forgetting to respond to your comment)
Thanks for the suggestion! That also looks good to me. I've reflected that comment at https://github.com/autowarefoundation/autoware-documentation/pull/127/commits/003895393879ee7e22425f11722ecd32bf62f568.

Any further comments on this? (cc. @kenji-miyake @soblin @shmpwk )

**Comment by kenji-miyake** [comment]
@kminoda Thank you for your proposal, but I don't understand the points well.

> For example, it is confusing to the readers that two pages with the exact same name of "planning simulation" exist both in the "Adhoc simulation" and "Scenario simulation" sections, because:

You can change the name, but as a fact, the "planning simulation" exists in both of them.
Also, I've explained the definitions of "Adhoc simulation" and "Scenario simulation" at the top page. There is a matrix of simulation patterns.

> the words "adhoc" and "scenario" themselves are (IMHO) not that common

But surely there are the concepts of "adhoc" and "scenario".

> This PR aims to provide more concrete titles for these subsections to clarify the goal of each page. To this end, I propose to rename the title of subsections as follows:

I'm confused with this proposal.
Why `scenario test` isn't named `simulation` even though it uses simulations? :thinking: 

image

**Comment by kminoda** [comment]
@kenji-miyake Thanks for the comments!
I understood that defining adhoc and scenario simulation in a similar way is reasonable so I would close this PR. I would instead consider proposing a better way to describe the difference between those two simulations.

**Pull request closed without merging**
